# Enable nested virtualization on Intel processors
options kvm_intel nested=1

# Nested virtualization support on AMD processors is not stable enough
# for production use, so disable it
options kvm_amd nested=0

# Do not automatically enable virt at kvm load
options kvm enable_virt_at_load=0
